apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ycfa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ycfa
    app.kubernetes.io/part-of: ci1t-43256-0059-app
  name: devfile-sample-ycfa
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ycfa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ycfa
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0059-tenant/ci1t-43256-0059-app/devfile-sample-ycfa@sha256:663d0ac787c1f58eec3ea58f58f4299cc490542147bed449f1a055c905203850
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
